name: Build and publish Docker image
on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push latest to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: eoepca/stac-manager:latest
          push: true
          build-args: |
            PRIMARY_COLOR='#005ACD',SECONDARY_COLOR='#048A81',STAC_API_URL='https://eoapi.develop.eoepca.org/stac'
      - name: Push tagged to Docker Hub
        uses: docker/build-push-action@v2
        if: github.ref_type == 'tag'
        with:
          tags: eoepca/stac-manager:${{ github.ref_name }}
          push: true
          secrets: |
            id=keycloak_url,src=${{ secrets.KEYCLOAK_URL }}
            id=keycloak_realm,src=${{ secrets.KEYCLOAK_REALM }}
            id=keycloak_client_id,src=${{ secrets.KEYCLOAK_CLIENT_ID }}
          build-args: |
            PRIMARY_COLOR='#005ACD',SECONDARY_COLOR='#048A81',STAC_API_URL='https://eoapi.develop.eoepca.org/stac'
